#!/bin/bash

ifconfig eth0 up
ifconfig eth0 172.16.60.254/24
route add -net 172.16.60.0/24 gw 172.16.60.1

ifconfig eth1 172.16.61.253/24
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 0 >  /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

route add default gw 172.16.61.254

echo -e "search netlab.fe.up.pt\nnameserver 172.16.1.1" > /etc/resolv.conf
